src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Book;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"},message="Cet email est déjà enregistré, veuillez en changer")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url()
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * Comparaison du champ ci-dessous avec le champ hash
     *
     * @Assert\EqualTo(propertyPath="hash",message="Les deux mots de passe ne correspondent pas.")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author", orphanRemoval=true)
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

     /**
     * @ORM\OneToMany(targetEntity="App\Entity\Book", mappedBy="booker")
     */
    private $books;
   
    public function getFullName(){

        return "{$this->firstname} {$this->lastname}";

    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->books = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * creation d'une fonction pour pemettre d'initialiser le slug avant la persistance et avant la maj
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */

    public function initialiseSlug(){
        if(empty($this->slug)){

            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstname.' '.$this->lastname);

        }
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }



    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles(){

        $roles = $this->userRoles->map(function($role){

            return $role->getTitle();

        })->toArray();

        $roles[]='ROLE_USER';

        return $roles;

    }

    public function getPassword(){

        return $this->hash;

    }

    public function getSalt(){}

    public function getUsername(){

        return $this->email;

    }

    public function eraseCredentials(){}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

     /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->setBooker($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->contains($book)) {
            $this->books->removeElement($book);
            // set the owning side to null (unless already changed)
            if ($book->getBooker() === $this) {
                $book->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

}

templates/inc/footer.html.twig
<section id="footer" class="row align-items-center justify-content-center">
        <div class="row col-md-12 justify-content-center">        
             <div class="row">       
                   <div>
                       <div class="contact"><h5>Informations</h5><hr></div>
                        <div id="infos">

                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                        </div>
                    </div>
                    <div>
                       <div class="contact"><h5>Nos services</h5><hr></div>
                        <div id="infos">

                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                            <p><a href=""><i class="fa fa-chevron-right"></i>lien</a></p>
                        </div>
                    </div>
                    <div>
                       <div class="contact"><h5>Contact</h5><hr></div>
                        <div id="infos">

                            <p><span>Email :</span><br>
                                email@email.com</p>
                            <p><span>Téléphone :</span><br>
                                01.25.35.39.95</p>
                            <p><span>Adresse :</span><br>
                            150 Rue du Marché<br>
                                75000 Paris</p>
                        </div>
                        </div>
                        <div>
                           <div class="contact"><h5>Réseaux Sociaux</h5><hr></div>
                            <div id="infos">

                                <p><i class="fab fa-facebook-square"></i>&nbsp;&nbsp; <a href="https://www.facebook.com/" target="_blank">Facebook</a></p>
                                <p><i class="fab fa-twitter-square"></i>&nbsp;&nbsp; <a href="https://twitter.com/login?lang=fr" target="_blank">Twitter</a></p>
                                <p><i class="fab fa-linkedin"></i>&nbsp;&nbsp; <a href="https://fr.linkedin.com/" target="_blank">Linkedin</a></p>
                                <p><i class="fab fa-pinterest-square"></i>&nbsp;&nbsp; <a href="https://www.pinterest.fr/pinterestfr/" target="_blank">Pinterest</a></p>
                                <p><i class="fa fa-rss"></i>&nbsp;&nbsp;&nbsp; <a href="#">RSS Feed</a></p>
                            </div>
                        </div>
                </div> 
            </div>
            <div class="row col-md-10 justify-content-center menubas">
                <ul class="nav">
                  <li class="nav-item">
                    <a class="nav-link active" href="{{ path('homepage') }}">Accueil</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}#cartemenu">Nos spécialités</a>
                  </li>
                   <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}#portfolio">Nos plats</a>
                  </li>
                   <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}#team">Notre équipe</a>
                  </li>
                   <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}#reservation">Réservation</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}#blog">Blog</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}#footer">Contact</a>
                  </li>
                </ul>
            </div>  
           <div class="row col-md-10 justify-content-center copyright">Copyright 2019. 
           </div>  
        </section>   

<script src="/js/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="/js/ad.js"></script>

templates/inc/header.html.twig
<!-- header -->
        <header id="header" class="row">
            <nav class="col-md-4 navbar navbar-expand-lg navbar-dark navleft">
                 <div class="navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <i class="fa fa-phone" aria-hidden="true"></i><span>00-000-000</span>
                            <i class="fa fa-phone" aria-hidden="true"></i><span>99-999-999</span>
                        </li>
                    </ul>
                </div>
            </nav>
            <nav class="col-md-4 navbar navbar-expand-lg navbar-dark navmiddle">
                 <div id="navbarColor01">
                    <ul class="navbar-nav ml-auto">  
                        <li class="nav-item dropdown">       
                            <i class="fa fa-envelope"></i><span class="align-self-left"><a href="#">email@email.com</a></span>
                        </li>
                    </ul>
                </div>
            </nav>

            
            <nav class="col-md-4 navbar navbar-expand-lg navbar-dark navhead pr-5">
            
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
               
                <ul class="navbar-nav ml-auto">

                        {% if app.user %}

                            <li class="nav-item dropdown">

                                <a href="#" class="nav-link dropdown-toggle" id="accountDropdownLink" data-toggle="dropdown">
                                    <img src="{{ app.user.avatar }}" alt="Avatar de {{ app.user.fullName }}" class="avatar avatar-small">
                                    <span class="ml-1">{{ app.user.fullName }}</span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right drophead" aria-labelledby="accountDropdownLink">
                    
                                <a class="dropdown-item" href="{{ path('account_home') }}">Mon compte</a>

                                <br>
                        
                                <a class="dropdown-item" href="{{ path('account_profile') }}">Editer mon profil</a>

                                <div class="dropdown-divider"></div>

                                <br>

                                <a class="dropdown-item" href="{{ path('account_books') }}">Mes réservations</a>

                                <br>

                                <div class="dropdown-divider"></div>

                                <br>
                                
                                <a class="dropdown-item" href="{{ path('account_bookings') }}">Mes commandes</a>

                                <br>

                                <div class="dropdown-divider"></div>
                    
                                <a class="dropdown-item" href="{{ path('account_logout') }}">Deconnexion</a>
                            </li>
                        
                        {% else %}

                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('account_register') }}">Inscription</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('account_login') }}">Connexion</a>
                            </li
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('admin_account_login') }}">Administration</a>
                            </li>

                         {% endif %}

                    </ul>
                </nav>
            
     
        </header>
        
        <section id="accueil" class="col-md-8 offset-md-2">
          <div class="barremenuhaut">
            <div class="row align-items-center justify-content-center px-3 py-3">
              <div class="">
                <a href="{{ path('homepage') }}"><img src="../img/logo.png"/></a>
              </div>
              <nav class="navbar navbar-expand-lg navbar-light bg-white">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link text-dark" href="{{ path('homepage') }}">Accueil <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Nos spécialités </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ path('homepage') }}#petit-dejeuner">Petit-Déjeuner</a>
                        <a class="dropdown-item" href="{{ path('homepage') }}#dejeuner">Déjeuner</a>
                        <a class="dropdown-item" href="{{ path('homepage') }}#diner">Diner</a>
                        <a class="dropdown-item" href="{{ path('homepage') }}#fastfood">Fast-Food</a>
                      <div class="dropdown-divider"></div>
                      </div>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" href="{{ path('homepage') }}#portfolio">Nos plats</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" href="{{ path('homepage') }}#team">Notre équipe</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" href="{{ path('homepage') }}#reservation">Réservation</a>
                    </li>
                    <li class="nav-item ">
                      <a class="nav-link text-dark" href="{{ path('homepage') }}#blog">Blog</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" href="{{ path('homepage') }}#footer">Contact</a>
                    </li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </section>
        

templates/inc/rating.html.twig
<span class="rating">
                                    {% for i in 1..5 %}
                                        {% if i <= rating %}
                                            <i class="fas fa-star"></i>
                                        {% else %}
                                            <i class="far fa-star"></i>
                                        {% endif %}
                                    {% endfor %}
                                </span>